megies/obspyck

CHANGELOG.txt
obspyck/obspyck.py
setup.py

..due to missing PAZ on traces (have `Response` objects attached instead).

Magnitude estimation for streams fetched from FDSN not working

---

obspyck/example.cfg
obspyck/util.py

- multiple station combinations can be specified on command line now.
so, station combinations in the config file can be made up more
logically structured
- reintroduce the possibility to specify a specific seed id to fetch on
command line (option '-i'/'--id', can be specified multiple times)

make selection of seed ids to fetch from servers more flexible

---

CHANGELOG.txt
obspyck/example.cfg
obspyck/obspyck.py

Tobias,
I realise it's possible to scroll and zoom in/out along the time axis using Shift + mouse-wheel. However, I haven't yet found a command to scroll/pan only (without any zoom). 
Is this possible?
Thanks,
S

Panning / scrolling along the time axis

---

CHANGELOG.txt
obspyck/example.cfg
obspyck/obspyck.py
obspyck/util.py

picking and saving to quakeml works, but interactions with location
routines etc. will probably very likely still only use pure 'P' and
'S' for now..

make it possible to use custom phases besides 'P' and 'S'

---

CHANGELOG.txt
obspyck/obspyck.py

These will plot as "foreign channel" picks in the normal Stream plot, i.e. they will not be associated to
any axes, as the axes/Traces/waveforms will always have a location code set. This implies that these picks won't ever be modifiable/deletable through the GUI..
Only solution I an think of right now to make them really accessible in the GUI would be to add an option to specify default location and channel codes for network/station combinations in the config file..
Fixes #49.

plot picks that don't have the location code specified (in the QuakeML file)

---

obspyck/example.cfg
obspyck/obspyck.py
obspyck/util.py

Matplotlib 2.0 has much thicker lines by default, which isn't ideal for picking, IMHO. This enables to control arbitrary matplotlibrc settings through config.

add possibility to control arbitrary matplotlibrc settings through config

---

obspyck/obspyck.py

during writing hyp2000 phases to file one station's picks could be
written twice and probably one station being omitted in turn

fix sorting of streams by distance/name

---

CHANGELOG.txt
obspyck/util.py

was still old obspy syntax that doesnt work on obspy 1.1.*

fix getting coordinates/PAZ from arclink

---

obspyck/example.cfg
obspyck/util.py

add possibility to specify complex, time-dependent station combinations

---

CHANGELOG.txt
obspyck/obspyck.py

just ignore them during plotting..
See #49, @ChrisBail let me know if this works for you..

avoid errors when encountering arrivals without time residual set

---

CHANGELOG.txt
obspyck/event_helper.py
obspyck/example.cfg
obspyck/obspyck.py

Hi,
Currently it is possible to plot the picks for one single event (the first one) of the quakeml file. Shall we consider the idea of plotting all the picks associated to multiple events (if t0 of all events are between starttime and endtime given in command line)? Is that out of scope of obspyck's philosophy?
Thanks,
Christian

Show picks for all events in QuakeML between given starttime & endtime

---

CHANGELOG.txt
obspyck/obspyck.py
obspyck/util.py

Always use `read_inventory()` / `Inventory`/`Response` objects for metadata, regardless if it comes from SEED (arclink) / XSEED (seishub) or STATIONXML (fdsn, ...).

Unify internal metadata handling

---

CHANGELOG.txt
obspyck/example.cfg
obspyck/obspyck.py

This PR adds support for obspy's AR picker again, which was dropped during the transition to the new canonical internal structure for handling event information.
CC @jwassermann
Currently only works with hardcoded AR picker parameters from obspyck config file (default location `~/.obspyckrc`), so parameters can not be tuned interactively in the GUI..

reimplement AR picker

---

CHANGELOG.txt
obspyck/obspyck.py
obspyck/util.py

I.e. in the plot 0.0s (origin of time/x-axis) is actually the time given on command line with option `-t`. Before, if an offset was given on command line, the 0-time in the plot was reference time shifted by offset.
This helps e.g. to easily read travel times if an origin time was given as reference time on command line.

make time axis origin be at given reference time always

---

CHANGELOG.txt
obspyck/obspyck.py
obspyck/util.py

save raw waveform data and station metadata in current obspyck instance's temporary directory for easy reuse (see #79)

save raw waveforms and metadata in tmp dir

---

obspyck/util.py

need to pass in bytes to subprocess' communicate() on Python 3

fix calling hyp2000 binary after py3 port

---

obspyck/event_helper.py

Somehow these imports worked before but not after Py3 port anymore, so import these submodules explicitely.

fix imports for quakeml reading after Python 3 port

---

CHANGELOG.txt
obspyck/obspyck.py

Also note there seems to be a (Py)Qt bug that causes Alt key not to work with mouse scrolling.

make the scroll wheel scaling factor from config affect all scroll events

---

CHANGELOG.txt
obspyck/obspyck.py
obspyck/rotate_to_zne.py
obspyck/util.py

- don't do rotation from original input data to ZNE during startup anymore(which comes before optional instrument), but rather do it on the fly whenswitching between streams and do it after optional instrument correction, sothat instrument correction works properly and doesn't have to rely on metadata attached to traces which might not be valid anymore if all three channels do not share the same response 
- get rid of some custom rotation code (that made it's way into obspy  years ago) and rather just use the obspy high level rotate command  and the complete Inventory for all data

Modernize rotate to ZNE

---

CHANGELOG.txt
obspyck/util.py

.. and use stock matplotlib init method. Seems like we had some hack that is not needed anymore and our patched code breaks with matplotlib >= 3.6

remove MultiCursor __init__ overwrite

---

CHANGELOG.txt
obspyck/obspyck.py

This could run into an error because `.get("..", {})` will still return a None value but if we chain another `.get()` after it we need a dict.

properly handle event creation info being None in some cases
